# Generated by Django 5.0.6 on 2024-06-29 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeEventos',
            fields=[
                ('id_informe_eventos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_generacion', models.DateField(auto_now_add=True)),
                ('cantidad_eventos', models.IntegerField()),
                ('eventos_realizados', models.IntegerField()),
                ('eventos_pendientes', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Informe de Eventos',
                'verbose_name_plural': 'Informes de Eventos',
                'db_table': 'informe_eventos',
            },
        ),
        migrations.CreateModel(
            name='InformeHabitaciones',
            fields=[
                ('id_informe_habitaciones', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_generacion', models.DateField(auto_now_add=True)),
                ('habitaciones_disponibles', models.IntegerField()),
                ('habitaciones_ocupadas', models.IntegerField()),
                ('habitaciones_total', models.IntegerField()),
                ('habitaciones_reservadas', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Informe de Habitaciones',
                'verbose_name_plural': 'Informes de Habitaciones',
                'db_table': 'informe_habitaciones',
            },
        ),
        migrations.CreateModel(
            name='InformeServicios',
            fields=[
                ('id_informe_servicios', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_generacion', models.DateField(auto_now_add=True)),
                ('total_servicios_vendidos', models.IntegerField()),
                ('cantidad_mas_vendido', models.IntegerField()),
                ('servicio_mas_vendido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mas_vendido', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Informe de Servicios',
                'verbose_name_plural': 'Informes de Servicios',
                'db_table': 'informe_servicios',
            },
        ),
    ]
