# Generated by Django 5.0.6 on 2024-06-26 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comodidad',
            fields=[
                ('id_comodidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Comodidad',
                'verbose_name_plural': 'Comodidades',
                'db_table': 'comodidad',
            },
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id_tipo_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de habitación',
                'verbose_name_plural': 'Tipos de Habitaciones',
                'db_table': 'tipo_habitacion',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id_hotel', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('descripcion', models.TextField(blank=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoteles_comunas', to='utilidades.comuna')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoteles_paises', to='utilidades.pais')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoteles_regiones', to='utilidades.region')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteles',
                'db_table': 'hotel',
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('numero_habitacion', models.CharField(max_length=10)),
                ('piso', models.PositiveIntegerField()),
                ('cantidad_camas', models.PositiveIntegerField(default=1)),
                ('cantidad_personas', models.PositiveIntegerField(default=1)),
                ('precio_por_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='habitaciones/')),
                ('id_comodidades', models.ManyToManyField(blank=True, related_name='habitaciones', to='hoteles.comodidad')),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='hoteles.hotel')),
                ('id_tipo_habitacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habitaciones', to='hoteles.tipohabitacion')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'db_table': 'habitacion',
                'unique_together': {('id_hotel', 'numero_habitacion')},
            },
        ),
    ]
