# Generated by Django 5.0.6 on 2024-06-29 00:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('hoteles', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaEvento',
            fields=[
                ('id_reserva_evento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Reserva de evento',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_clientes', to='clientes.cliente')),
                ('id_metodo_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_metodos_clientes', to='clientes.metodopago')),
                ('id_tarjeta_credito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_tarjetas_clientes', to='clientes.tarjetacredito')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='ReservaHabitacion',
            fields=[
                ('id_reserva_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=10)),
                ('referencia', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_cliente', to='clientes.cliente')),
                ('id_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_habitaciones', to='hoteles.habitacion')),
            ],
            options={
                'verbose_name': 'Reserva de habitación',
                'verbose_name_plural': 'Reserva de habitaciones',
                'db_table': 'reserva_habitacion',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comentario', to='clientes.cliente')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comentario', to='reservas.reservahabitacion')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'comentario',
            },
        ),
        migrations.CreateModel(
            name='ReservaServicioAsociado',
            fields=[
                ('id_reserva_servicio_asociado', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='reservas.reservahabitacion')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Servicio Asociado a Reserva',
                'verbose_name_plural': 'Servicios Asociados a Reserva',
                'db_table': 'servicio_asociado_reserva',
            },
        ),
    ]
