# Generated by Django 5.0.6 on 2024-06-26 23:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hoteles', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=10)),
                ('referencia', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('id_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='hoteles.habitacion')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='ReservaServicioAsociado',
            fields=[
                ('id_reserva_servicio_asociado', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='reservas.reserva')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Servicio Asociado a Reserva',
                'verbose_name_plural': 'Servicios Asociados a Reserva',
                'db_table': 'servicio_asociado_reserva',
            },
        ),
    ]
